#########################
# DO NOT EDIT THIS FILE #
#########################

# Imports from external libraries
import numpy as np

# Imports from this project
import two_dim.constants as constants
import two_dim.config as config


# The environment class defines where the robot starts, where the goal is, and where the obstacle is.
class Environment:

    # Initialisation of a new environment
    def __init__(self):
        # Same environment for each episode
        if config.ENVIRONMENT_TYPE == 'fixed':
            # Obstacle position
            self.obstacle_pos = np.array([0.55, 0.45])
            self.obstacle_radius = 0.25
            # Initial state
            self.init_state = np.array([0.2, 0.3])
            # Goal state
            self.goal_state = np.array([0.9, 0.9])
            # Set the current state to the initial state
            self.state = self.init_state

        # Different environment for each episode
        elif config.ENVIRONMENT_TYPE == 'random':
            # Goal state
            self.goal_state = np.array([0.9, 0.9])
            done = False
            while not done:
                # Obstacle position
                obstacle_pos_x = np.random.uniform(constants.OBSTACLE_POSITION_RANGE[0][0], constants.OBSTACLE_POSITION_RANGE[0][1])
                obstacle_pos_y = np.random.uniform(constants.OBSTACLE_POSITION_RANGE[1][0], constants.OBSTACLE_POSITION_RANGE[1][1])
                self.obstacle_pos = np.array([obstacle_pos_x, obstacle_pos_y])
                self.obstacle_radius = np.random.uniform(constants.OBSTACLE_RADIUS_RANGE[0], constants.OBSTACLE_RADIUS_RANGE[1])
                # Initial state
                self.init_state = np.random.uniform(0.1, 0.9, 2)
                # Check for intersection between the initial state and the obstacle
                radius_sum = self.obstacle_radius + constants.ROBOT_RADIUS
                distance_to_obstacle = np.hypot(self.init_state[0] - self.obstacle_pos[0], self.init_state[1] - self.obstacle_pos[1])
                if distance_to_obstacle > radius_sum:
                    done = True
            # Set the current state to the initial state
            self.state = self.init_state

        else:
            # Raise an error if the environment type is not valid
            raise ValueError("config.ENVIRONMENT_TYPE is invalid.")

    # Reset the environment, i.e. set the state to the initial state
    def reset(self):
        self.state = self.init_state

    # Step the environment by executing one action
    def step(self, action):
        next_state = self.dynamics(self.state, action)
        self.state = next_state
        return next_state

    # The environment dynamics, i.e. the transition function
    def dynamics(self, state, action):
        # First, clip the action in each dimension
        action = np.clip(action, -constants.MAX_ACTION_MAGNITUDE, constants.MAX_ACTION_MAGNITUDE)
        # The dynamics is a simple sum
        next_state = state + action
        # Check if the robot is inside the obstacle
        intersection = self.intersects_circle(state, next_state, self.obstacle_pos, self.obstacle_radius)
        if intersection:
            # If there is an intersection, set the state to just before the point of intersection
            direction = (state - next_state) / np.linalg.norm(state - next_state)
            next_state = intersection + 0.0001 * direction
            return next_state
        # Check if the robot is past the boundary
        intersection = self.intersects_perimeter(state, next_state)
        if intersection:
            # If there is an intersection, set the state to just before the point of intersection
            direction = (state - next_state) / np.linalg.norm(state - next_state)
            next_state = intersection + 0.0001 * direction
            return next_state
        # Otherwise, if the robot is inside the environment and not within the obstacle, return the next state as calculated before
        return next_state

    # Function to check if a line intersects the circle obstacle
	# Returns None if the line doesn’t intersect with the circle
    # Otherwise returns the intersection point
    def intersects_circle(self, p1, p2, center, r):
        (x1, y1), (x2, y2) = p1, p2
        cx, cy = center
        dx, dy = x2 - x1, y2 - y1
        # shift to circle coordinates
        fx, fy = x1 - cx, y1 - cy
        a = dx * dx + dy * dy
        b = 2 * (fx * dx + fy * dy)
        c = fx * fx + fy * fy - r * r
        disc = b * b - 4 * a * c
        if disc < 0:
            return None
        sqrt_disc = np.sqrt(disc)
        t1 = (-b - sqrt_disc) / (2 * a)
        t2 = (-b + sqrt_disc) / (2 * a)
        hits = [(t, (x1 + t * dx, y1 + t * dy)) for t in (t1, t2) if 0 <= t <= 1]
        return min(hits)[1] if hits else None

    # Function to check if a line intersects the environment perimeter
    # Returns None if the segment doesn’t hit the square’s perimeter
	# Otherwise returns the intersection point
    def intersects_perimeter(self, p1, p2):
        x1, y1 = p1
        x2, y2 = p2
        dx, dy = x2 - x1, y2 - y1
        hits = []
        if dx:
            for x in (0.0, 1.0):
                t = (x - x1) / dx
                if 0 <= t <= 1:
                    y = y1 + t * dy
                    if 0 <= y <= 1:
                        hits.append((t, (x, y)))
        if dy:
            for y in (0.0, 1.0):
                t = (y - y1) / dy
                if 0 <= t <= 1:
                    x = x1 + t * dx
                    if 0 <= x <= 1:
                        hits.append((t, (x, y)))
        return min(hits)[1] if hits else None
