#########################
# DO NOT EDIT THIS FILE #
#########################

# Imports from external libraries
import numpy as np

# Imports from this project
import one_dim.constants as constants
import one_dim.config as config


# The environment class defines where the robot starts, where the goal is, and where the obstacle is.
class Environment:

    # Initialisation of a new environment
    def __init__(self):
        # Same environment for each episode
        if config.ENVIRONMENT_TYPE == 'fixed':
            # Initial state
            self.init_state = np.array([0.2])
            # Goal state
            self.goal_state = np.array([0.9])
            # Set the current state to the initial state
            self.state = self.init_state
        else:
            # Raise an error if the environment type is not valid
            raise ValueError("config.ENVIRONMENT_TYPE is invalid.")

    # Reset the environment, i.e. set the state to the initial state
    def reset(self):
        self.state = self.init_state

    # Step the environment by executing one action
    def step(self, action):
        next_state = self.dynamics(self.state, action)
        self.state = next_state
        return next_state

    # The environment dynamics, i.e. the transition function
    def dynamics(self, state, action):
        # First, clip the action in each dimension
        action = np.clip(action, -constants.MAX_ACTION_MAGNITUDE, constants.MAX_ACTION_MAGNITUDE)
        # The dynamics is a simple sum
        next_state = state + action
        # Check if the robot is past the boundary
        intersection = self.intersects_perimeter(state, next_state)
        if intersection:
            # If there is an intersection, set the state to just before the point of intersection
            direction = (state - next_state) / np.linalg.norm(state - next_state)
            next_state = intersection + 0.0001 * direction
            return next_state
        # Otherwise, if the robot is inside the environment and not within the obstacle, return the next state as calculated before
        return next_state

    # Function to check if a line intersects the environment perimeter
    # Returns None if the segment doesn’t hit the square’s perimeter
	# Otherwise returns the intersection point
    def intersects_perimeter(self, x1, x2):
        if x2 < -1.0:
            return -1.0
        elif x2 > 1.0:
            return 1.0