#########################
# DO NOT EDIT THIS FILE #
#########################

# Imports from external libraries
import time
import numpy as np
import pygame

# Imports from this project
from one_dim.environment import Environment
from one_dim.robot import Robot
from one_dim.graphics import Graphics
import one_dim.config as config


# Set the numpy random seed
if config.RANDOM_SEED == 0:
    seed = int(time.time())
else:
    seed = config.RANDOM_SEED
np.random.seed(seed)
# Initialize pygame
pygame.init()
# Create an environment (the "physical" world)
environment = Environment()
# Create a robot (the robot's "brain" making the decisions) and reset the episode
robot = Robot()
# Create a graphics object (this will create a window and draw on the window)
graphics = Graphics()


# Main loop
running = True
while running:
    # Check for any user input
    for event in pygame.event.get():
        # Closing the window
        if event.type == pygame.QUIT:
            running = False
    # Robot selects an action, and decides whether it has finished the episode
    curr_state = np.copy(environment.state)
    action, episode_done = robot.select_action(curr_state)
    # If the episode has finished, create a new environment
    if episode_done:
        environment = Environment()
        robot.reset()
    # If the episode has not finished, execute the selected action
    else:
        next_state = environment.step(action)
    # Draw the environment, and any visualisations, on the window
    graphics.draw(environment, robot.visualisations)

# If we have broken out of the main loop, quite pygame and end the program
pygame.quit()
